### ISSUE TITLE
fail build in linux

### ISSUE THREAD

**Issue by sl1pkn07** [DJATOM/VapourSynth-TColorMask#1]
Hi

fail build in linux with GCC 10.2

~~~make
g++ -c -fPIC -march=native -O2 -pipe -fno-plt -D_FORTIFY_SOURCE=2 -I. -I/usr/include/vapoursynth  -o TColorMask.o TColorMask/TColorMask.cpp
TColorMask/TColorMask.cpp: In function 'int stringToInt(const string&)':
TColorMask/TColorMask.cpp:126:12: error: no match for 'operator[]' (operand types are 'const string' {aka 'const std::__cxx11::basic_string<char>'} and 'int')
  126 |     if (str[0] == '$') {
      |            ^
TColorMask/TColorMask.cpp:127:23: error: invalid use of incomplete type 'const string' {aka 'const class std::__cxx11::basic_string<char>'}
  127 |         auto substr = str.substr(1, str.length());
      |                       ^~~
In file included from /usr/include/c++/10.2.0/iosfwd:39,
                 from /usr/include/c++/10.2.0/memory:74,
                 from TColorMask/TColorMask.cpp:3:
/usr/include/c++/10.2.0/bits/stringfwd.h:74:11: note: declaration of 'std::string' {aka 'class std::__cxx11::basic_string<char>'}
   74 |     class basic_string;
      |           ^~~~~~~~~~~~
TColorMask/TColorMask.cpp:127:37: error: invalid use of incomplete type 'const string' {aka 'const class std::__cxx11::basic_string<char>'}
  127 |         auto substr = str.substr(1, str.length());
      |                                     ^~~
In file included from /usr/include/c++/10.2.0/iosfwd:39,
                 from /usr/include/c++/10.2.0/memory:74,
                 from TColorMask/TColorMask.cpp:3:
/usr/include/c++/10.2.0/bits/stringfwd.h:74:11: note: declaration of 'std::string' {aka 'class std::__cxx11::basic_string<char>'}
   74 |     class basic_string;
      |           ^~~~~~~~~~~~
TColorMask/TColorMask.cpp:130:19: error: invalid use of incomplete type 'const string' {aka 'const class std::__cxx11::basic_string<char>'}
  130 |     return strtol(str.c_str(), 0, 10);
      |                   ^~~
In file included from /usr/include/c++/10.2.0/iosfwd:39,
                 from /usr/include/c++/10.2.0/memory:74,
                 from TColorMask/TColorMask.cpp:3:
/usr/include/c++/10.2.0/bits/stringfwd.h:74:11: note: declaration of 'std::string' {aka 'class std::__cxx11::basic_string<char>'}
   74 |     class basic_string;
      |           ^~~~~~~~~~~~
TColorMask/TColorMask.cpp: In function 'void TCMCreate(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*)':
TColorMask/TColorMask.cpp:215:72: error: invalid use of incomplete type 'std::string' {aka 'class std::__cxx11::basic_string<char>'}
  215 |             throw std::string{ "Only 8 bit YUV formats are supported!" };
      |                                                                        ^
In file included from /usr/include/c++/10.2.0/iosfwd:39,
                 from /usr/include/c++/10.2.0/memory:74,
                 from TColorMask/TColorMask.cpp:3:
/usr/include/c++/10.2.0/bits/stringfwd.h:74:11: note: declaration of 'std::string' {aka 'class std::__cxx11::basic_string<char>'}
   74 |     class basic_string;
      |           ^~~~~~~~~~~~
TColorMask/TColorMask.cpp:220:60: error: invalid initialization of reference of type 'const string&' {aka 'const std::__cxx11::basic_string<char>&'} from expression of type 'const char*'
  220 |             colors.push_back(stringToInt(vsapi->propGetData(in, "colors", i, &err)));
      |                                          ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
TColorMask/TColorMask.cpp:125:36: note: in passing argument 1 of 'int stringToInt(const string&)'
  125 | int stringToInt(const std::string &str) {
      |                 ~~~~~~~~~~~~~~~~~~~^~~
TColorMask/TColorMask.cpp:300:32: error: invalid use of incomplete type 'const string' {aka 'const class std::__cxx11::basic_string<char>'}
  300 |     catch (const std::string & error) {
      |                                ^~~~~
In file included from /usr/include/c++/10.2.0/iosfwd:39,
                 from /usr/include/c++/10.2.0/memory:74,
                 from TColorMask/TColorMask.cpp:3:
/usr/include/c++/10.2.0/bits/stringfwd.h:74:11: note: declaration of 'std::string' {aka 'class std::__cxx11::basic_string<char>'}
   74 |     class basic_string;
      |           ^~~~~~~~~~~~
TColorMask/TColorMask.cpp:301:48: error: 'error' was not declared in this scope; did you mean 'err'?
  301 |         vsapi->setError(out, ("TColorMask: " + error).c_str());
      |                                                ^~~~~
      |                                                err
make: *** [Makefile:2: all] Error 1
~~~

greetings

**Comment by DJATOM** [comment]
Guess I can slightly overhaul it in January... I have no time in December, sorry.
PRs are also welcome.

**Comment by DJATOM** [comment]
@sl1pkn07 Uploaded a fix, it was easy thing in the end.
Could you please check if it builds on arch? I have tested latest msvc and gcc10.2.1-mingw, both works on my end.

**Comment by sl1pkn07** [comment]
build ok.

tnx a lot and happy new year :)
